services:
  visionx-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8501:8501"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 5s
      timeout: 3s
      retries: 3
