version: 2.1

orbs:
  docker: circleci/docker@2.1
  slack: circleci/slack@4.5.0 # Include Slack Orb for notifications

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: default
          docker_layer_caching: true
      - run:
          name: Docker login
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $REGISTRY
      - run:
          name: Build and push Docker image
          command: |
            LOWERCASE_IMAGE_NAME=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')
            docker build -t $REGISTRY/$LOWERCASE_IMAGE_NAME:latest .
            docker push $REGISTRY/$LOWERCASE_IMAGE_NAME:latest
      - slack/notify:
          event: fail # Send notification if the build fails
          template: basic_fail_1
      - slack/notify:
          event: pass # Send notification if the build passes
          template: basic_success_1

  scan:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Trivy
          command: |
            sudo apt-get install wget apt-transport-https gnupg lsb-release
            wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
            echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
            sudo apt-get update && sudo apt-get install trivy
      - run:
          name: Scan Docker image for vulnerabilities
          command: |
            LOWERCASE_IMAGE_NAME=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')
            trivy image --severity HIGH,CRITICAL $REGISTRY/$LOWERCASE_IMAGE_NAME:latest
      - slack/notify:
          event: fail # Send notification if the scan fails
          template: basic_fail_1
      - slack/notify:
          event: pass # Send notification if the scan passes
          template: basic_success_1

workflows:
  version: 2
  build-scan:
    jobs:
      - build
      - scan:
          requires:
            - build
